
export const ARTICLE_LIST_REQUEST = 'ARTICLE_LIST_REQUEST';
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS';
export const ARTICLE_LIST_FAIL = 'ARTICLE_LIST_FAIL';
export const ARTICLE_LIST_UPDATE = 'ARTICLE_LIST_UPDATE';
export const ARTICLE_LIST_MORE = 'ARTICLE_LIST_MORE';

export const ARTICLE_LIST_LOAD_MORE_REQUEST = 'ARTICLE_LIST_LOAD_MORE_REQUEST';
export const ARTICLE_LIST_LOAD_MORE_SUCCESS = 'ARTICLE_LIST_LOAD_MORE_SUCCESS';
export const ARTICLE_LIST_LOAD_MORE_FAIL = 'ARTICLE_LIST_LOAD_MORE_FAIL';

export const ARTICLE_YOUR_LIST_REQUEST = 'ARTICLE_YOUR_LIST_REQUEST';
export const ARTICLE_YOUR_LIST_SUCCESS = 'ARTICLE_YOUR_LIST_SUCCESS';
export const ARTICLE_YOUR_LIST_FAIL = 'ARTICLE_YOUR_LIST_FAIL';
export const ARTICLE_YOUR_LIST_DELETE = 'ARTICLE_YOUR_LIST_DELETE';
export const ARTICLE_YOUR_LIST_UPDATE = 'ARTICLE_YOUR_LIST_UPDATE';
export const ARTICLE_YOUR_LIST_MORE = 'ARTICLE_YOUR_LIST_MORE';

export const ARTICLE_LIST_FAVORITE_REQUEST = 'ARTICLE_LIST_FAVORITE_REQUEST';
export const ARTICLE_LIST_FAVORITE_SUCCESS = 'ARTICLE_LIST_FAVORITE_SUCCESS';
export const ARTICLE_LIST_FAVORITE_FAIL = 'ARTICLE_LIST_FAVORITE_FAIL';
export const ARTICLE_LIST_FAVORITE_UPDATE = 'ARTICLE_LIST_FAVORITE_UPDATE';
export const ARTICLE_LIST_FAVORITE_MORE = 'ARTICLE_LIST_FAVORITE_MORE';

export const ARTICLE_LIST_FEED_REQUEST = 'ARTICLE_LIST_FEED_REQUEST';
export const ARTICLE_LIST_FEED_SUCCESS = 'ARTICLE_LIST_FEED_SUCCESS';
export const ARTICLE_LIST_FEED_UPDATE = 'ARTICLE_LIST_FEED_UPDATE';
export const ARTICLE_LIST_FEED_FAIL = 'ARTICLE_LIST_FEED_FAIL';
export const ARTICLE_LIST_FEED_MORE = 'ARTICLE_LIST_FEED_MORE';

export const ARTICLE_CREATE_REQUEST = 'ARTICLE_CREATE_REQUEST';
export const ARTICLE_CREATE_SUCCESS = 'ARTICLE_CREATE_SUCCESS';
export const ARTICLE_CREATE_FAIL = 'ARTICLE_CREATE_FAIL';
export const ARTICLE_CREATE_RESET = 'ARTICLE_CREATE_RESET';

export const ARTICLE_UPDATE_REQUEST = 'ARTICLE_UPDATE_REQUEST';
export const ARTICLE_UPDATE_SUCCESS = 'ARTICLE_UPDATE_SUCCESS';
export const ARTICLE_UPDATE_FAIL = 'ARTICLE_UPDATE_FAIL';
export const ARTICLE_UPDATE_RESET = 'ARTICLE_CREATE_RESET';

export const ARTICLE_DETAILS_REQUEST = 'ARTICLE_DETAILS_REQUEST';
export const ARTICLE_DETAILS_SUCCESS = 'ARTICLE_DETAILS_SUCCESS';
export const ARTICLE_DETAILS_UPDATE = 'ARTICLE_DETAILS_UPDATE';
export const ARTICLE_DETAILS_FAIL = 'ARTICLE_DETAILS_FAIL';

export const ARTICLE_POPULAR_REQUEST = 'ARTICLE_POPULAR_REQUEST';
export const ARTICLE_POPULAR_SUCCESS = 'ARTICLE_POPULAR_SUCCESS';
export const ARTICLE_POPULAR_UPDATE = 'ARTICLE_POPULAR_UPDATE';
export const ARTICLE_POPULAR_FAIL = 'ARTICLE_POPULAR_FAIL';

export const ARTICLE_FAVORITE_REQUEST = 'ARTICLE_FAVORITE_REQUEST';
export const ARTICLE_FAVORITE_SUCCESS = 'ARTICLE_FAVORITE_SUCCESS';
export const ARTICLE_FAVORITE_FAIL = 'ARTICLE_FAVORITE_FAIL';

export const ARTICLE_UNFAVORITE_REQUEST = 'ARTICLE_UNFAVORITE_REQUEST';
export const ARTICLE_UNFAVORITE_SUCCESS = 'ARTICLE_UNFAVORITE_SUCCESS';
export const ARTICLE_UNFAVORITE_FAIL = 'ARTICLE_UNFAVORITE_FAIL';
export const ARTICLE_UNFAVORITE_RESET = 'ARTICLE_UNFAVORITE_RESET';

export const ARTICLE_RELATIVE_TAG_REQUEST = 'ARTICLE_RELATIVE_TAG_REQUEST';
export const ARTICLE_RELATIVE_TAG_SUCCESS = 'ARTICLE_RELATIVE_TAG_SUCCESS';
export const ARTICLE_RELATIVE_TAG_UPDATE = 'ARTICLE_RELATIVE_TAG_UPDATE';
export const ARTICLE_RELATIVE_TAG_FAIL = 'ARTICLE_RELATIVE_TAG_FAIL';

export const ARTICLE_RELATIVE_AUTHOR_REQUEST = 'ARTICLE_RELATIVE_AUTHOR_REQUEST';
export const ARTICLE_RELATIVE_AUTHOR_SUCCESS = 'ARTICLE_RELATIVE_AUTHOR_SUCCESS';
export const ARTICLE_RELATIVE_AUTHOR_UPDATE = 'ARTICLE_RELATIVE_AUTHOR_UPDATE';
export const ARTICLE_RELATIVE_AUTHOR_FAIL = 'ARTICLE_RELATIVE_AUTHOR_FAIL';

export const ARTICLE_DELETE_REQUEST = 'ARTICLE_DELETE_REQUEST';
export const ARTICLE_DELETE_SUCCESS = 'ARTICLE_DELETE_SUCCESS';
export const ARTICLE_DELETE_FAIL = 'ARTICLE_DELETE_FAIL';
export const ARTICLE_DELETE_RESET = 'ARTICLE_DELETE_RESET';

export const ARTICLE_NEW_LIST_REQUEST = 'ARTICLE_NEW_LIST_REQUEST';
export const ARTICLE_NEW_LIST_SUCCESS = 'ARTICLE_NEW_LIST_SUCCESS';
export const ARTICLE_NEW_LIST_FAIL = 'ARTICLE_NEW_LIST_FAIL';

export const ARTICLE_SEARCH_REQUEST = 'ARTICLE_SEARCH_REQUEST';
export const ARTICLE_SEARCH_SUCCESS = 'ARTICLE_SEARCH_SUCCESS';
export const ARTICLE_SEARCH_UPDATE = 'ARTICLE_SEARCH_UPDATE';
export const ARTICLE_SEARCH_FAIL = 'ARTICLE_SEARCH_FAIL';
export const ARTICLE_SEARCH_MORE = 'ARTICLE_SEARCH_MORE';

export const ARTICLE_SEARCH_RELATIVE_REQUEST = 'ARTICLE_SEARCH_RELATIVE_REQUEST';
export const ARTICLE_SEARCH_RELATIVE_SUCCESS = 'ARTICLE_SEARCH_RELATIVE_SUCCESS';
export const ARTICLE_SEARCH_RELATIVE_FAIL = 'ARTICLE_SEARCH_RELATIVE_FAIL';