export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST';
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';
export const COMMENT_CREATE_FAIL = 'COMMENT_CREATE_FAIL';
export const COMMENT_CREATE_RESET = 'COMMENT_CREATE_RESET';

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAIL = 'COMMENT_DELETE_FAIL';
export const COMMENT_DELETE_RESET = 'COMMENT_DELETE_RESET';

export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';
export const COMMENT_LIST_CREATE_UPDATE = 'COMMENT_LIST_CREATE_UPDATE';
export const COMMENT_LIST_DELETE_UPDATE = 'COMMENT_LIST_DELETE_UPDATE';
export const COMMENT_LIST_DELETE = 'COMMENT_LIST_DELETE';
export const COMMENT_LIST_CREATE = 'COMMENT_LIST_CREATE';
export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL';
export const COMMENT_LIST_MORE = 'COMMENT_LIST_MORE';

export const COMMENT_LIST_LOAD_MORE_REQUEST = 'COMMENT_LIST_LOAD_MORE_REQUEST';
export const COMMENT_LIST_LOAD_MORE_SUCCESS = 'COMMENT_LIST_LOAD_MORE_SUCCESS';
export const COMMENT_LIST_LOAD_MORE_FAIL = 'COMMENT_LIST_LOAD_MORE_FAIL';