export const TAG_LIST_REQUEST = 'TAG_LIST_REQUEST';
export const TAG_LIST_SUCCESS = 'TAG_LIST_SUCCESS';
export const TAG_LIST_FAIL = 'TAG_LIST_FAIL';

export const TAG_SEARCH_REQUEST = 'TAG_SEARCH_REQUEST';
export const TAG_SEARCH_SUCCESS = 'TAG_SEARCH_SUCCESS';
export const TAG_SEARCH_MORE = 'TAG_SEARCH_MORE';
export const TAG_SEARCH_FAIL = 'TAG_SEARCH_FAIL';

export const TAG_SEARCH_RELATIVE_REQUEST = 'TAG_SEARCH_RELATIVE_REQUEST';
export const TAG_SEARCH_RELATIVE_SUCCESS = 'TAG_SEARCH_RELATIVE_SUCCESS';
export const TAG_SEARCH_RELATIVE_FAIL = 'TAG_SEARCH_RELATIVE_FAIL';

export const TAG_LIST_LOAD_MORE_REQUEST = 'TAG_LIST_LOAD_MORE_REQUEST';
export const TAG_LIST_LOAD_MORE_SUCCESS = 'TAG_LIST_LOAD_MORE_SUCCESS';
export const TAG_LIST_LOAD_MORE_FAIL = 'TAG_LIST_LOAD_MORE_FAIL';