export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const ACCOUNT_ACTIVATE_REQUEST = 'ACCOUNT_ACTIVATE_REQUEST';
export const ACCOUNT_ACTIVATE_SUCCESS = 'ACCOUNT_ACTIVATE_SUCCESS';
export const ACCOUNT_ACTIVATE_FAIL = 'ACCOUNT_ACTIVATE_FAIL';
export const ACCOUNT_ACTIVATE_RESET = 'ACCOUNT_ACTIVATE_RESET';

export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const USER_FORGOT_PASSWORD_FAIL = 'USER_FORGOT_PASSWORD_FAIL';
export const USER_FORGOT_PASSWORD_RESET = 'USER_FORGOT_PASSWORD_RESET';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_RESET = 'RESET_PASSWORD_RESET';

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST';
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL';
export const USER_DETAIL_RESET = 'USER_DETAIL_RESET';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST';
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS';
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL';

export const USER_UNFOLLOW_REQUEST = 'USER_UNFOLLOW_REQUEST';
export const USER_UNFOLLOW_SUCCESS = 'USER_UNFOLLOW_SUCCESS';
export const USER_UNFOLLOW_FAIL = 'USER_UNFOLLOW_FAIL';

export const USER_FOLLOW_LIST_REQUEST = 'USER_FOLLOW_LIST_REQUEST';
export const USER_FOLLOW_LIST_SUCCESS = 'USER_FOLLOW_LIST_SUCCESS';
export const USER_FOLLOW_LIST_UPDATE = 'USER_FOLLOW_LIST_UPDATE';
export const USER_FOLLOW_LIST_MORE = 'USER_FOLLOW_LIST_MORE';
export const USER_FOLLOW_LIST_FAIL = 'USER_FOLLOW_LIST_FAIL';

export const USER_UNFOLLOW_LIST_REQUEST = 'USER_UNFOLLOW_LIST_REQUEST';
export const USER_UNFOLLOW_LIST_SUCCESS = 'USER_UNFOLLOW_LIST_SUCCESS';
export const USER_UNFOLLOW_LIST_UPDATE = 'USER_UNFOLLOW_LIST_UPDATE';
export const USER_UNFOLLOW_LIST_MORE = 'USER_UNFOLLOW_LIST_MORE';
export const USER_UNFOLLOW_LIST_FAIL = 'USER_UNFOLLOW_LIST_FAIL';

export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST';
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS';
export const USER_SEARCH_UPDATE = 'USER_SEARCH_UPDATE';
export const USER_SEARCH_MORE = 'USER_SEARCH_MORE';
export const USER_SEARCH_FAIL = 'USER_SEARCH_FAIL';

export const USER_SEARCH_RELATIVE_REQUEST = 'USER_SEARCH_RELATIVE_REQUEST';
export const USER_SEARCH_RELATIVE_SUCCESS = 'USER_SEARCH_RELATIVE_SUCCESS';
export const USER_SEARCH_RELATIVE_UPDATE = 'USER_SEARCH_RELATIVE_UPDATE';
export const USER_SEARCH_RELATIVE_FAIL = 'USER_SEARCH_RELATIVE_FAIL';

export const USER_MAIL_SIGNUP_REQUEST = 'USER_MAIL_SIGNUP_REQUEST';
export const USER_MAIL_SIGNUP_SUCCESS = 'USER_MAIL_SIGNUP_SUCCESS';
export const USER_MAIL_SIGNUP_FAIL = 'USER_MAIL_SIGNUP_FAIL';

export const USER_LIST_LOAD_MORE_REQUEST = 'USER_LIST_LOAD_MORE_REQUEST';
export const USER_LIST_LOAD_MORE_SUCCESS = 'USER_LIST_LOAD_MORE_SUCCESS';
export const USER_LIST_LOAD_MORE_FAIL = 'USER_LIST_LOAD_MORE_FAIL';